install:
    sudo apt install python3 -y
    sudo apt install python3-pip -y
    sudo apt install nmap -y
    sudo pip3 install -r requirements.txt

clean:
    sudo apt purge python3 -y
    sudo apt purge python3-pip -y
    sudo apt purge nmap -y
    sudo pip3 uninstall -r requirements.txt